# Generated by Django 5.0.4 on 2024-05-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=25, null=True)),
                ('alias', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
